### ISSUE TITLE
Error on CP -> settings -> route.

### ISSUE THREAD

**Issue by GMConsultant** [craft-snippets/craft-named-routes#3]
Hi there, thank you for writing this plugin that works perfectly in the front end. 
The problem occurs if I try to configure a new route in the control panel and this is the error that appears:
```

Twig\Error\RuntimeError: Neither the property "getProjectConfigRoutes" nor one of the methods "getProjectConfigRoutes()", "getgetProjectConfigRoutes()"/"isgetProjectConfigRoutes()"/"hasgetProjectConfigRoutes()" or "__call()" exist and have public access in class "craftsnippets\craftnamedroutes\variables\CraftNamedRoutesVariable". in /home/mydomain/craft/vendor/craftcms/cms/src/templates/settings/routes.twig:33
Stack trace:
#0 /home/mydomain/craft/vendor/craftcms/cms/src/helpers/Template.php(129): twig_get_attribute()
#1 /home/mydomain/craft/storage/runtime/compiled_templates/7c/7ced1ab61802cf4d4c2a526dfdd5ec07.php(54): craft\helpers\Template::attribute()
#2 /home/mydomain/craft/vendor/twig/twig/src/Template.php(394): __TwigTemplate_0325ca502202c1c4b40f6c7d5e42ee6e->doDisplay()
#3 /home/mydomain/craft/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#4 /home/mydomain/craft/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#5 /home/mydomain/craft/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#6 /home/mydomain/craft/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render()
#7 /home/mydomain/craft/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render()
#8 /home/mydomain/craft/vendor/craftcms/cms/src/web/View.php(535): craft\web\View->renderTemplate()
#9 /home/mydomain/craft/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate()
#10 /home/mydomain/craft/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\TemplateResponseFormatter->format()
#11 /home/mydomain/craft/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#12 /home/mydomain/craft/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#13 /home/mydomain/craft/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#14 /home/mydomain/craft/web_cp/index.php(12): yii\base\Application->run()
#15 {main}

```
Obviously if I disable it the error disappears and I can access to the routes configuration.

**Server  configuration:**

- PHP version 8.1.2
- Linux 5.15.0-84-generic
- MariaDB 10.6.12
- Craft Pro 4.5.14
- Named routes 2.0.0

**Comment by piotrpog** [comment]
Thanks for pointing this out. Will take care of it soon.

**Comment by piotrpog** [comment]
@GMConsultant 
Sorry for the delay. Just released update with fix to this error. This was due to plugin registering "craft.routes" template variable which conflicted with one used in craft control panel "routes" page.
